{% comment %}
    
    Welcome to the BaseSpace Report Builder!
    
    Click the "Help" button above for information on how to use the DotLiquid
    language to access data from the results generated by your app.
 
    This is your default result template. You can enable or disable
    templates by selecting the "Options" button above.
    
    Below, we've included example code that demonstrates how to list the
    files present in this result, and a link to the BaseSpace CSS,
    which is based on the Twitter Bootstrap library.
        
    -The BaseSpace team
    Feedback: https://developer.basespace.illumina.com/community/feedback

{% endcomment %}

<td>{{ result.files["atacseeker.html"] | append: "bar" }}</td>

{% for key in result.files %}
<iframe src={{ result.files[key].href }} frameborder="0" style="overflow:hidden;height:100%;width:100%" height="100%" width="100%">
</iframe>
{% endfor %}