#!/bin/sh

SUBJ=`basename $1 .bam`
GENOME=${2:-"hg19"}
CHROM_SIZES="chrom.sizes/"$GENOME".chrom.sizes"

## if we don't already have chrom.sizes for the genome in question, fetch them
test -f $CHROM_SIZES || ./fetchChromSizes $GENOME > $CHROM_SIZES

echo -n "Creating coverage bedgraph for $SUBJ..."
genomeCoverageBed -bg -split -ibam $SUBJ.bam -g $CHROMSIZES > $SUBJ.cov.bg && \
  bedGraphToBigWig $SUBJ.cov.bg $CHROM_SIZES $SUBJ.Signal.bw && \
  rm $SUBJ.cov.bg 
echo "...done."
